### PR TITLE
Add ieSafe option to fall back on ie-incompatible files

### PR DESCRIPTION
**Pull request by kgram**
This option falls back to the file-loader if the file contains a style-element and the encoded size is above 4kB no matter the `limit` specified.

Here is [a fiddle](https://jsfiddle.net/kgram/f048tc0j/) demonstrating the problem.

Should help solve #92.

### CODE REVIEW

**Comment by kgram** [comment]
I'm not sure about the name. I also just noticed all the other options are all lowercase, so at least that should probably be fixed. Any thoughts?

**Comment by evilebottnawi** [comment]
@bhovhannes friendly ping

**Comment by bhovhannes** [comment]
@kgram, thank you for your contribution! 
Your PR fixes #92, which is a long standing one.
I agree regarding name. Let's make it lowercase to avoid any confusion. Otherwise your PR looks good for me.

**Comment by kgram** [comment]
@bhovhannes it should be in order now.

**Comment by bhovhannes** [comment]
Released as 2.2.0

**Pull request merged**
